services:
  backend:
    build: .
    ports:
      - "4000:3000"
    volumes:
      - .:/app

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./~mysql:/var/lib/mysql
    ports:
      - "3307:3306"
